### ISSUE TITLE
Crafting Table Advancement bug

### ISSUE THREAD

**Issue by DanteAyagawe** [pr1kol/Oblivion-of-the-Galaxy#3] opened 2021-01-28 00:40 UTC
I can’t seem to update the advancement on the crafting table part, it’s still currently grated out unlike the other advancements, and I don’t know what advancement this is to just get it by command and progress, does it have to do with fastworkbench mod?

**Comment by pr1kol** [comment] 2021-01-28 06:11
Hello, so that I can understand the problem in more detail, can you describe it more specifically and send me some screenshots?

**Comment by DanteAyagawe** [comment] 2021-01-28 16:09
I don’t have the screenshots yet, but to give you more details to it, the advancement was, “break a wood log with your barehands and create a crafting table to progress” did that, used cheats for all kinds of wood log, break them all by hand, made wood planks then crafting table, but the advancement was still grayed out

**Comment by DanteAyagawe** [comment] 2021-01-28 16:11
Like no advancement popped out that I made the crafting table, lucking i progressed onto the infuser on mekanism, but that advancement haunts me

**Comment by pr1kol** [comment] 2021-01-29 18:54
I understood what the problem is, this is an error in the advancements code. This will be fixed in the next version of the modpack.
Thanks for your help in finding bugs.

**Comment by pr1kol** [comment] 2021-02-03 07:55
In the new version 3.0 of Modpack, everything is fixed. =)
Thanks for your help in finding bugs.

**Closed by pr1kol** 2021-02-03 07:55 UTC
Labels: bug
